Updating thigs a but after a long time. Every module is going to have a setup script. There are some pending of being created.

diff --git a/find_extsd b/find_extsd
--- a/find_extsd
+++ b/find_extsd
@@ -1,7 +1,12 @@
 #!/bin/bash
 
-
 source bash_helpers.sh
+
+if ! [[ -v BASH_HELPERS_LOADED ]];
+then
+    echo -e "BASH helpers not found in PATH. Install it first.\n"
+    exit 1
+fi
 
 
 if [[ "$TERMUX_VERSION" == "" ]];
diff --git a/proots/new_proot b/proots/new_proot
--- a/proots/new_proot
+++ b/proots/new_proot
@@ -2,6 +2,12 @@
 
 source bash_helpers.sh
 
+if ! [[ -v BASH_HELPERS_LOADED ]];
+then
+    echo -e "BASH helpers not found in PATH. Install it first.\n"
+    exit 1
+fi
+
 
 usage()
 {
@@ -38,24 +44,9 @@ echo "Checking for proot-distro updates ..."
 echo "-------------------------------------"
 
 pkg update
-pkg upgrade -y
+pkg upgrade proot-distro -y
 
 echo ""
-
-
-if ! [[ -f "$PREFIX/bin/proot-distro" ]];
-then
-    echo "Installing proot-distro ..."
-    echo "---------------------------"
-
-    pkg install -y proot-distro
-
-    if ! [ "$?" == "0" ];
-    then
-        echo ""
-        abort "Failed!"
-    fi
-fi
 
 
 if [[ "$PROOT_DISTRO" == "" ]];
diff --git a/proots/pexec_admin b/proots/pexec_admin
--- a/proots/pexec_admin
+++ b/proots/pexec_admin
@@ -2,6 +2,12 @@
 
 source bash_helpers.sh
 
+if ! [[ -v BASH_HELPERS_LOADED ]];
+then
+    echo -e "BASH helpers not found in PATH. Install it first.\n"
+    exit 1
+fi
+
 
 usage()
 {
@@ -23,7 +29,7 @@ then
 fi
 
 
-if [ "$1" == "-h" ] || [ "$1" == "--help" ];
+if [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]];
 then
     usage
     abort
